spring.application.name=alfa-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/alfacontrol
spring.datasource.username=postgres
spring.datasource.password=vikas@1470

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
